### PR TITLE
add notes for building on windows under Mingw and Cygwin

### PR DESCRIPTION
**Pull request by fangdingjun**
some notes for building on windows under Mingw and Cygwin environment.

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you.  @fangdingjun : could you fix typo reported by @alagoutte ?

**Comment by fangdingjun** [comment]
I fix the typo and add a missing command in the sample command, please review it. Thanks.

**Comment by tatsuhiro-t** [comment]
Looks good.  Will merge soon.

**Comment by tatsuhiro-t** [comment]
Thank you!  Merged now.

**Pull request merged**
