### PR TITLE
Graceful shutdown and joinable server

### PR DESCRIPTION
**Pull request by sunxiaoguang**
Make it possible to shutdown server gracefully and also joinable.

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you for PR!
Clearly this breaks current API usage.   I suggest that we should preserve behavior of http2::listen_and_server (that is, block in listen_and_serve forever) and we can add detached version "listen_and_serve" where programmer can call http2::join() wherever they like.

It would be good to rebase the commits, since b2ce8ac is somewhat duplicated.

**Comment by sunxiaoguang** [comment]
So I'm going to add a extra argument to specify if the server should be started in async mode or not. Do you prefer changing function signature to add an argument with default value or add a new method with one more argument. Adding new method doesn't break ABI, but add redundancy. Not sure which way you prefer. I would choose whatever the way you feel more comfortable with.

**Comment by tatsuhiro-t** [comment]
I'm OK with adding parameter with default value.
asio lib is still not entirely stable right now, so ABI breakage is acceptable for now.

**Comment by sunxiaoguang** [comment]
Sure, I will do it that way.

**Comment by sunxiaoguang** [comment]
Committed, please review

**Comment by tatsuhiro-t** [comment]
Thank you!  Reviewing now...

**Comment by tatsuhiro-t** [comment]
Merged now.  Thank you very much.

**Comment by sunxiaoguang** [comment]
It's my pleasure.

**Pull request merged**
