### PR TITLE
libnghttp2_asio: Added io_service accessors

### PR DESCRIPTION
**Pull request by apohl79**
To allow the asio wrapper to work with boost.fiber it is required
to access the underlying io_service objects.

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you!
BTW, we have http2::io_service() method to get underlying io_service object for the connection.  Do you think that is not enough to support boost fiber?   Does it need all io_service objects?

**Comment by apohl79** [comment]
Yes thats true, I will update this to const. Thx!

Regarding your question. Yes - we need access to all io_service objects unfortunately, as we have to install a timer on each of them to allow a fiber scheduler on each worker thread to work.

**Comment by tatsuhiro-t** [comment]
Thank you!  Merged now.

**Comment by apohl79** [comment]
Great thanks!
On Dec 10, 2015 13:29, Tatsuhiro Tsujikawa <notifications@github.com> wrote:Thank you!  Merged now.

**Pull request merged**
