### PR TITLE
[WIP] nghttpx: mruby extension

### PR DESCRIPTION
**Pull request by tatsuhiro-t**
Just for my personal interest, I'm writing mruby extension to nghttpx.
I made several commit so far, and it now can hook request phase and response phase by mruby script file, given in --on-request-mruby-file and --on-response-mruby-file options.

The current API is experimental.  Although we have no documentation for it, we will write it soon.
If you are interested in this, please join the discussion.

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Oh, forgot to mention that we need libmruby-dev installed to compile this nghttpx-mruby branch.

**Comment by tatsuhiro-t** [comment]
Renamed option names as --request-phase-file and --response-phase-file respectively.

Here are some example code.  To replace existing request header field:

```ruby
Nghttpx.run do |resp, req|
    req.set_header "user-agent", "Netscape 4.0.7; Linux 2.0"
end
```

Returning custom response:

```ruby
Nghttpx.run do |resp, req|
    # return custom response with 401 status code if request path is /secret
    if req.path == '/secret'
        resp.clear_headers
        resp.status = 401
        resp.return "you are not authorized to view this content"
    end
end
```

**Comment by tatsuhiro-t** [comment]
I also added test cases.  After writing documentation, then this is ready to merge.

**Comment by matsumoto-r** [comment]
It's very interesting!!

**Comment by tatsuhiro-t** [comment]
@matsumoto-r yeah, exploring possibility with mruby is great fun.
I still have to figure out how mruby works..

**Comment by tatsuhiro-t** [comment]
OK, so I added env.ctx which is Ruby hash, and persists request lifetime:
```ruby
Nghttpx.run do |env|
    env.ctx['msg'] = 'bloody aweful'
end
```

**Comment by tatsuhiro-t** [comment]
The bad news is that we have to build mruby for our own with C++ ABI enabled.
libmruby packaged in Debian/Ubuntu does not enable C++ ABI.  That means that mruby exception does not destroy C++ object allocated on the stack, which brings quite undefined behaviour.

**Comment by matsumoto-r** [comment]
Oh... bad news :(

**Comment by tatsuhiro-t** [comment]
mruby is bundled through git submodule.  Now it works with out of tree build as well.
Documentation for mruby API has been done as well.
Now it is really ready for merge.

**Comment by tatsuhiro-t** [comment]
Merged!
mruby support is disabled by default.
To enable it, pull latest master, and run `git submodule update --init`, and `./configure --with-mruby`.
And `make`.

**Pull request merged**
