### PR TITLE
Map /dev/stdout and /dev/stderr to their descriptors.

### PR DESCRIPTION
**Pull request by thinred**
This seems to do the trick for the issue #325.

It may also be used to simplify the Android-specific workarounds with /proc/self/df/2.

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you for PR!
We need to set CLOEXEC flag to new file descriptor from dup.
Since it is a bit difficult to make this happen atomically, perhaps we can treat /dev/stderr and /dev/stdout specially in reopen_log_files in shrpx_log.cc so that we just use STDERR_FILENO and STDOUT_FILENO without opening additional file descriptors.

**Comment by thinred** [comment]
Oh, right, there are some forks here and there in the code. Actually I wanted to do as you say, but then I figured out that instead of reopening the file I can simply "reopen" the descriptor. I seemed clean and simpler to me. We can use dup3() to set O_CLOEXEC automatically, too. :)

**Comment by tatsuhiro-t** [comment]
We have already some #if-def code to support platform which lacks O_CLOEXEC flag.  For that platform, descriptor may leak depending on the severe timing of fork.  So it is ok to use O_CLOEXEC to dup3 and provide replacement code for other platforms.  That said, in portability point of view, it is better not to use dup3 if we can avoid it...

**Comment by thinred** [comment]
I wonder whether there are platforms that have O_CLOEXEC, but no dup3(). Well, anyway, I'll cook something without it. Stay tuned.

**Comment by thinred** [comment]
Hi again,
please review this. As a bonus, a patch on top of this removes some android-specific code which is now obsolete.

**Comment by thinred** [comment]
There is still a small issue with the code (and it existed even before, actually).
In redirect_stderr_to_errorlog, the stderr fd is replaced with errorlog_fd and so stderr is closed. Now, if we execv the process with updated configuration it *may* happen that the errorlog is from a regular file to stderr once again, but this won't work since stderr was already closed.
I believe that a solution is to dup stderr early in the program and use it instead.

**Comment by thinred** [comment]
I've pushed some more code, I haven't tested the last commit, because I'd like to know what you think.

**Comment by tatsuhiro-t** [comment]
Thank you.  I completely missed this issue.  I agree with your idea for the fix.  It seems it is working fine.

**Comment by tatsuhiro-t** [comment]
@thinred Do you think these commits are ready to merge?

**Comment by thinred** [comment]
They solve the problem for me and I'm fairly confident that they don't break anything.
I'd say yes.

**Comment by tatsuhiro-t** [comment]
OK, thank you.  I also tested this and worked fine for me.  Merged now.

**Pull request merged**
