### PR TITLE
Add TLS dynamic record size behaviour command line options

### PR DESCRIPTION
**Pull request by LPardue**
First go at changes to address #393 

Feedback appreciated. I've passed 0 values in memcached construction, not sure if thats appropriate. Maybe constructor overload for Connection?

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Awesome!  I'll review this PR, and leave comments if any.

**Comment by tatsuhiro-t** [comment]
> I've passed 0 values in memcached construction, not sure if thats appropriate.

It is ok.  Currently, we don't use TLS for memcached connection.

> Maybe constructor overload for Connection?

C++11 delegating constructor can be used here, but I'm fine with the current proposed code.

**Comment by tatsuhiro-t** [comment]
The patch works really good!

**Comment by LPardue** [comment]
> The dynamic record sizing is enabled for all frontend connections, including HTTP/1 and SPDY as well as HTTP/2 if TLS is configured.

I think in the old version of nghttpx it was only supported in HTTP/2, goes to show the rate of development on this project, great stuff!

> The patch works really good!
Good code quality + design means everything was in place to make this change and test it. I will address your commits and update the PR over the next day.

**Comment by LPardue** [comment]
If this looks ok I can squash ready for merge

**Comment by tatsuhiro-t** [comment]
Looks good to me!

**Comment by LPardue** [comment]
squashed and ready!

**Comment by tatsuhiro-t** [comment]
Thank you!  Merged now.

**Pull request merged**
