### PR TITLE
improved malloc error handlings.

### PR DESCRIPTION
**Pull request by cubicdaiya**

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you for the PR!  Could you take a look my comment?

**Comment by cubicdaiya** [comment]
I fixed by reference to your comment. How about this?

**Comment by tatsuhiro-t** [comment]
Looks good.  Thank you!  Will merge soon.

**Comment by tatsuhiro-t** [comment]
Thank you, merged now.

**Pull request merged**
