### PR TITLE
msvc build fixes and enchantments.

### PR DESCRIPTION
**Pull request by mindw**
* fix build broken by recent changes
* place all build artifacts to OBJDIR
* explicitly add manifest (VC9/10)
* modernize python bindings creation
* some minor refactoring

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you for PR.
It seems NGHTTP2_EXTERN is only required in header files, and not needed in .c file.
I checked other projects (specifically, libcurl), it only uses CURL_EXTERN (NGHTTP2_EXTERN counterpart) in header files.
Can you confirm this? I could be missing something.

**Comment by mindw** [comment]
No, not really :)

**Comment by tatsuhiro-t** [comment]
Thanks.   lib/nghttp2_hd.c should be also updated too (it still includes NGHTTP2_EXTERN).

**Comment by mindw** [comment]
Yes. Fixed now.

**Comment by tatsuhiro-t** [comment]
Thank you!  Merged now.

**Pull request merged**
