### PR TITLE
Windows build fixes for #195

### PR DESCRIPTION
**Pull request by remoe**
- source file list updated
- zlib removed
- build of .def files removed

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Thank you! Merged now.

**Comment by Elavarasan83** [comment]
Hello,
I'm compiling sources of Apache web server in windows x64 machine. Apache web server has dependency to nghttp2. I want to build nghttp2 in windows x64 machine. 

I have some questions:

1. Is the "Makefile.msvc' in 'lib' folder of nghttp2 is up to date? If not then what are are all the sections i have to update whenever I get a new version of nghttp2. I see 'nghttp2_rcbuf.c' is missing in 'NGHTTP2_SRC' section.

2. Apache expects .lib and not the .dll. I assume the output generated will have .lib file of nghttp2.

3.  In https://github.com/nghttp2/nghttp2, it is mentioned 'libevent' is necessary & also the macro '__STRICT_ANSI__' to be undefined. I think these steps are necessary only when we use cygwin. Am I right?

4.  The below mentioned nmake command is sufficient to generate the output or any othe configuration is required.
  **C:\nghttp2\lib>** _nmake /f Makefile.msvc_

Please clarify.

**Comment by tatsuhiro-t** [comment]
> 1. Is the "Makefile.msvc' in 'lib' folder of nghttp2 is up to date? If not then what are are all the sections i have to update whenever I get a new version of nghttp2. I see 'nghttp2_rcbuf.c' is missing in 'NGHTTP2_SRC' section.

I suppose so.  I see nghttp2_rcbuf.c in Makefile.msvc in master branch

> 2 Apache expects .lib and not the .dll. I assume the output generated will have .lib file of nghttp2.

This Makefile was contributed by users, and I haven't executed it since I don't have the Windows development environment.  Did you see that it only produced dll, and not .lib file?

> 3 In https://github.com/nghttp2/nghttp2, it is mentioned 'libevent' is necessary & also the macro 'STRICT_ANSI' to be undefined. I think these steps are necessary only when we use cygwin. Am I right?

libevent is required to compile the programs under examples.  Makefile.msvc only compiles libnghttp2, so you don't need libevent.

I think STRICT_ANSI stuff is for cygwin, but I may be wrong.

> 4 The below mentioned nmake command is sufficient to generate the output or any othe configuration is required. The command will be run using to VS2013 x64 native tools command prompt.
C:\nghttp2\lib> nmake /f Makefile.msvc

The comment from Makefile.msvc says it is for "GNU Makefile for nghttp2 / MSVC", so it may require GNU Make.

**Comment by Elavarasan83** [comment]
Dear tatsuhiro-t,
Thanks for the quick response. I will install GNU make and do the compilation

**Pull request merged**
